version: "3.1"

services:
  frontend:
    image: localhost:5000/skivrige.writing/frontend
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    image: localhost:5000/skivrige.writing/backend
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: localhost:5000/skivrige.writing/nginx
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '8081:80'